"""add unique constraints

Revision ID: c64c11ad46c8
Revises: 971ef8955fbb
Create Date: 2026-02-09 13:43:49.392639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64c11ad46c8'
down_revision: Union[str, Sequence[str], None] = '971ef8955fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_answers_submission_qidx', 'answers', ['submission_id', 'question_index'])
    op.create_unique_constraint('uq_eval_submission_type', 'evaluations', ['submission_id', 'evaluator_type'])
    op.create_unique_constraint('uq_submissions_exam_student', 'submissions', ['exam_id', 'student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_submissions_exam_student', 'submissions', type_='unique')
    op.drop_constraint('uq_eval_submission_type', 'evaluations', type_='unique')
    op.drop_constraint('uq_answers_submission_qidx', 'answers', type_='unique')
    # ### end Alembic commands ###
